import = [ "/usr/lib/node_modules/alacritty-themes/themes/Kitty.toml" ]

[window]
opacity = 0.9
decorations = "Full"
decorations_theme_variant = "Dark"

  [window.padding]
  x = 5
  y = 5

[font]
size = 14

  [font.normal]
  family = "Hack Nerd Font Mono"
