import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Tokyonight_Night.toml"
]

[window]
opacity = 1
decorations = "Full"
decorations_theme_variant = "Dark"

  [window.padding]
  x = 5
  y = 5

[font]
size = 14

  [font.normal]
  family = "Hack Nerd Font Mono"
