[general]
import = [
  "/usr/lib/node_modules/alacritty-themes/themes/Tokyonight_Night.toml"
]

[window]
opacity = 1

  [window.padding]
  x = 5
  y = 5

[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 12

  [font.normal]
  family = "Hack Nerd Font Mono"
